#!/usr/bin/env python3
"""Build marola.dev/docs/ — one index over the guides, the MIPs and the generated API docs.

Deliberately not split by language: a reader wants "where is marola's documentation", not "which
compiler produced it". The API trees are one section among several. MIP-0044 §5.6.

Markdown docs are linked to the repository rather than mirrored into the site: publishing
docs/*.md is the disclosure decision MIP-0044 §5.5 gates on MIP-0033 §5.1's repo-public checklist,
which is not this script's call to make.

    scripts/build_docs_index.py --out out/docs/index.html
    scripts/build_docs_index.py --self-test
"""

from __future__ import annotations

import argparse
import html
import re
import sys
from pathlib import Path

REPO = "https://github.com/h0ffmann/marola/blob/main"

GUIDES = [
    ("PHILOSOPHY.md", "Why marola is built the way it is"),
    ("docs/ARCHITECTURE.md", "The pipeline, the six pluggable integrations, what is verified live"),
    ("docs/RUN-LOCALLY.md", "Run it now with Ollama — no account, no key"),
    ("docs/DEV-FLOW.md", "The development loop end to end"),
    ("docs/EFFECTS-MAP.md", "What is pure, what is effectful, what is hidden"),
    ("docs/FUTURE-WORK.md", "Design sketches and reviewed-but-not-adopted ideas"),
    ("docs/ROADMAP.md", "What to do next, and why"),
    ("AGENTS.md", "The rules any AI agent working here follows"),
]

MODULES = [
    ("core", "pipeline logic, scoring, the pluggable traits"),
    ("local", "Ollama-backed implementations, the water-quality parsers"),
    ("azure", "the opt-in Azure integrations"),
    ("cli", "Main, AppConfig, the MCP tool server"),
]

MIP_RE = re.compile(r"^MIP-(\d{4})-(.+)\.md$")


def mips(mips_dir: Path) -> list[tuple[str, str, str]]:
    """(number, slug-as-title, filename) for every MIP on disk, by number."""
    found = []
    for f in sorted(mips_dir.glob("MIP-*.md")) if mips_dir.is_dir() else []:
        m = MIP_RE.match(f.name)
        if not m:
            continue
        found.append((m.group(1), m.group(2).replace("-", " "), f.name))
    return found


def render(guides, module_list, mip_list) -> str:
    def li(href, name, note):
        note_html = f" <small>— {html.escape(note)}</small>" if note else ""
        return f'    <li><a href="{html.escape(href)}">{html.escape(name)}</a>{note_html}</li>'

    guide_items = "\n".join(li(f"{REPO}/{p}", Path(p).name, note) for p, note in guides)
    # marola.html, not index.html: scaladoc's landing page lists only "Packages: package marola",
    # so linking it lands the reader on an empty body. The package page is the actual content.
    api_items = "\n".join(li(f"api/scala/{m}/marola.html", m, note) for m, note in module_list)
    mip_items = "\n".join(
        li(f"{REPO}/docs/mips/{fn}", f"MIP-{num} — {title}", "") for num, title, fn in mip_list
    )
    return f"""<!doctype html>
<meta charset="utf-8">
<title>marola — documentation</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
  body {{ font: 16px/1.6 system-ui, sans-serif; margin: 3rem auto; max-width: 46rem; padding: 0 1rem; color: #16242c; }}
  h1 {{ font-size: 1.5rem; margin-bottom: .2rem }}
  h2 {{ font-size: 1.05rem; margin-top: 2.2rem; border-bottom: 1px solid #dde4e8; padding-bottom: .3rem }}
  ul {{ list-style: none; padding: 0 }}
  li {{ margin: .45rem 0 }}
  a {{ color: #0b6e99; text-decoration: none }}
  a:hover {{ text-decoration: underline }}
  small {{ color: #5c6b73 }}
  p.lede {{ color: #5c6b73; margin-top: 0 }}
</style>
<h1>marola — documentation</h1>
<p class="lede">Guides and design docs live in the repository; the API docs below are regenerated by
CI whenever the code changes.</p>

<h2>Guides</h2>
<ul>
{guide_items}
</ul>

<h2>API — Scala</h2>
<ul>
{api_items}
</ul>

<h2>API — Python</h2>
<ul>
    <li><a href="api/python/index.html">scripts</a> <small>— the repo's own tooling</small></li>
</ul>
<p><small>Nine stdlib-only CLI scripts rather than a library: roughly a third of their functions
carry docstrings. Read it as a tour of the tooling, not a reference.</small></p>

<h2>Improvement proposals ({len(mip_list)})</h2>
<p><small>Every non-trivial change is designed here before it is built.</small></p>
<ul>
{mip_items}
</ul>
"""


def self_test() -> int:
    fails = 0

    def ok(got, want, label):
        nonlocal fails
        if got == want:
            print(f"  ok   {label}")
        else:
            fails += 1
            print(f"  FAIL {label} — got {got!r}, want {want!r}")

    page = render(
        [("PHILOSOPHY.md", "why")],
        [("core", "logic")],
        [("0044", "site sections", "MIP-0044-site-sections.md")],
    )
    ok(
        'href="api/scala/core/marola.html"' in page,
        True,
        "Scala modules link to the package page, which has the members",
    )
    ok(
        'href="api/scala/core/index.html"' in page,
        False,
        "and not to scaladoc's landing page, whose body is one 'package marola' line",
    )
    ok(
        'href="api/python/index.html"' in page,
        True,
        "the Python docs are one section, not a separate site",
    )
    ok("/dev/" in page, False, "no /dev/ path — the docs live at /docs/")
    ok(f"{REPO}/PHILOSOPHY.md" in page, True, "guides link to the repository, not a mirrored copy")
    ok(f"{REPO}/docs/mips/MIP-0044-site-sections.md" in page, True, "MIPs are listed and linked")
    ok("MIP-0044 — site sections" in page, True, "a MIP's slug becomes a readable title")
    ok('src="http' in page, False, "the index itself loads no external script")
    ok(
        mips(Path("/definitely/absent")),
        [],
        "a missing mips directory yields no entries, not a crash",
    )
    if fails:
        print(f"build_docs_index self-test: {fails} failure(s)", file=sys.stderr)
        return 1
    print("build_docs_index self-test: ok")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--out", type=Path)
    ap.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parent.parent)
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args(argv)
    if args.self_test:
        return self_test()
    if not args.out:
        ap.print_help()
        return 2
    page = render(GUIDES, MODULES, mips(args.repo_root / "docs" / "mips"))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(page, encoding="utf-8")
    print(f"wrote {args.out} ({len(page)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
